- hosts: gm
  tasks:
    - name: 检查 gm 目录
      shell: "find /data -maxdepth 1 -type d -name 'gmserver[0-9]*' -printf '%f\n'"
      register: gm_list
      changed_when: false

    - name: 分发更新压缩包
      copy:
        src: "{{ playbook_dir }}/../../file/increment.tar.gz"
        dest: /data/update/increment.tar.gz

    - name: 删除原本的 app 目录
      file:
        path: /data/update/app
        state: absent

    - name: 执行解压
      unarchive:
        src: /data/update/increment.tar.gz
        dest: /data/update/
        remote_src: yes

    - name: 动态处理 gm 实例
      include_tasks: gm.yaml
      loop: "{{ gm_list.stdout_lines }}"
      loop_control:
        loop_var: gm_item