- name: 复制文件
  copy:
    src: /data/update/app/
    dest: /data/{{ gm_item }}/
    remote_src: yes

- name: 过滤 {{ gm_item }} 进程
  shell: pgrep -af '/data/{{ gm_item }}/p8_app_server'
  register: gm_stat
  ignore_errors: yes

- name: Reload gm 进程（若存在）
  shell: "./server.sh reload"
  args:
    chdir: "/data/{{ gm_item }}/"
  when: gm_stat.rc == 0