- name: 复制文件
  shell: "command cp -rf /data/update/app/* /data/{{ gm_item }}/"
  tags:
    - increment
    - alldo

- name: 过滤 {{ gm_item }} 进程
  shell: pgrep -af '/data/{{ gm_item }}/p8_app_server'
  register: gm_stat
  ignore_errors: yes
  tags:
    - increment
    - alldo

- name: Reload gm 进程（若存在）
  shell: "./server.sh reload"
  args:
    chdir: "/data/{{ gm_item }}/"
  when: gm_stat.rc == 0
  tags:
    - increment
    - alldo
