- hosts: global
  tasks:
    - name: 检查 global 目录
      shell: "find /data/center/ -maxdepth 1 -type d -name 'global*' -printf '%f\n'"
      register: global_list
      changed_when: false
      tags:
        - alldo
      
    - name: 分发更新压缩包
      copy:
        src: "{{ playbook_dir }}/../../file/alldo.tar.gz"
        dest: /data/update/alldo.tar.gz
      tags:
        - alldo

    - name: 删除原本的 app 目录
      file:
        path: /data/update/app
        state: absent
      tags:
        - alldo

    - name: 执行解压
      unarchive:
        src: /data/update/alldo.tar.gz
        dest: /data/update/
        remote_src: yes
      tags:
        - alldo

    - name: 动态处理 global 实例
      include_tasks: global.yaml
      loop: "{{ global_list.stdout_lines }}"
      loop_control:
        loop_var: global_item
      tags:
        - alldo