- hosts: "{{host_name}}"
  tasks:
    - name: 检查 login 目录
      shell: "find /data/server/ -maxdepth 1 -type d -name 'login*' -printf '%f\n'"
      register: login_list
      changed_when: false

    - name: 重启每个 login 实例
      shell: "./server.sh reload && sleep 3"
      args:
        chdir: /data/server/{{ login_item }}/
      loop: "{{ login_list.stdout_lines }}"