- hosts: "{{ host_name }}"
  vars:
    open_time: "{{ lookup('pipe', 'date +\"%Y-%m-%dT%H:01:00\"') }}"
  tasks:
    - name: 1-0 检查/data/serverX/目录是否存在
      stat:
        path: "/data/server{{ area_id }}"
      register: dir_check
    
    - name: 1-1 目录不存在时终止剧本
      fail:
        msg: "目录 /data/server{{ area_id }} 不存在，停止剧本执行"
      when: not dir_check.stat.exists
    
    - name: 1-2 分发时间文件
      template:
        src: templates/open_time.lua.j2
        dest: "/data/server{{ area_id }}/game/lua/config/open_time.lua"
    
    - name: 1-3 初始检测进程状态
      shell: "pgrep -f /data/server{{ area_id }}/game/p8_app_server"
      register: svc_stat
      ignore_errors: yes
    
    - name: 1-4 进程存活时执行Reload
      shell: "./server.sh reload && sleep 1 && ./server.sh reload && sleep 1"
      args:
        chdir: "/data/server{{ area_id }}/game/"
      when: svc_stat.rc == 0
    
    - name: 1-5 进程不存在时尝试启动
      shell: "./server.sh start && sleep 3"
      args:
        chdir: "/data/server{{ area_id }}/game/"
      when: svc_stat.rc != 0

    - name: 1-6 最终检测进程状态
      shell: "pgrep -f /data/server{{ area_id }}/game/p8_app_server"
      register: start_attempt
      ignore_errors: yes
    
    - name: 1-7 验证服务最终状态
      fail:
        msg: "服务未运行，操作后仍无法启动"
      when: start_attempt.rc != 0