- hosts: "{{ host_name }}"
  tasks:
    - name: 1-1 修改白名单
      shell: "sed -i -e '/{{ white_num }}/d' -e '/^$/d' /data/server/login/etc/white_list.txt"

    - name: 1-2 检查进程状态
      shell: pgrep -f /data/server/login/p8_app_server
      register: p8_stat
      ignore_errors: yes

    - name: 1-3 尝试启动服务（若未运行）
      shell: "./server.sh start && sleep 3"
      args:
        chdir: /data/server/login/
      register: start_stat
      when: p8_stat.rc != 0

    - name: 1-4 重新加载配置（若进程已运行）
      shell: "./server.sh reload && sleep 3"
      args:
        chdir: /data/server/login/
      when: p8_stat.rc == 0

    - name: 1-5 最终进程检查
      shell: pgrep -f /data/server/login/p8_app_server
      register: final_stat
      ignore_errors: yes

    - name: 1-6 验证服务状态
      fail:
        msg: "服务未运行，尝试后仍无法启动"
      when: final_stat.rc != 0
