- name: 复制文件
  copy:
    src: /data/update/app/
    dest: /data/{{ game_item }}/game/
    remote_src: yes
  tags: increment

- name: 过滤 {{ game_item }} 进程
  shell: pgrep -af '/data/{{ game_item }}/game/p8_app_server'
  register: game_stat
  ignore_errors: yes
  tags:
    - groups
    - increment

- name: Reload game 进程（若存在）
  shell: "./server.sh reload"
  args:
    chdir: "/data/{{ game_item }}/game/"
  when: game_stat.rc == 0
  tags:
    - groups
    - increment