- hosts: game
  tasks:
    - name: 检查 game 目录
      shell: "find /data -maxdepth 1 -type d -name 'server[0-9]*' -printf '%f\n'"
      register: game_list
      changed_when: false

    - name: 分发 groups.lua 到 game
      copy:
        src: groups.lua
        dest: "/data/{{ item }}/game/etc/groups.lua"
        mode: 0644
      loop: "{{ game_list.stdout_lines }}"
      tags: groups

    - name: 分发更新压缩包
      copy:
        src: "{{ playbook_dir }}/../../file/increment.zip"
        dest: /data/update/increment.zip
      tags: increment

    - name: 删除原本的 app 目录
      file:
        path: /data/update/app
        state: absent

    - name: 执行解压
      unarchive:
        src: /data/update/increment.zip
        dest: /data/update/
        remote_src: yes
        mode: '0644'
        directory_mode: '0755'
      tags: increment

    - name: 动态处理 game 实例
      include_tasks: game.yaml
      loop: "{{ game_list.stdout_lines }}"
      loop_control:
        loop_var: game_item