- hosts: "{{ host_name }}"
  tasks:
    # ========== login ==========
    - name: 检测login进程
      shell: "pgrep -f /data/server/login/p8_app_server"
      register: login_stat
      ignore_errors: yes
      tags:
        - login-stop

    - name: 执行停止login
      shell: "./server.sh stop && sleep 3"
      args:
        chdir: /data/server/login/
      when: login_stat.rc == 0
      tags:
        - login-stop

    # ========== 启动login ==========
    - name: login复制更新包
      copy:
        src: /data/update/full/
        dest: "/data/server/login/"
        remote_src: yes
      tags:
          - login-start

    - name: 清理login下nohup.txt
      file:
        path: /data/server/login/nohup.txt
        state: absent
      tags:
        - login-start

    - name: 启动login
      shell: "./server.sh start && sleep 3"
      args:
        chdir: /data/server/login/
      tags:
        - login-start

    - name: 验证login状态
      shell: "pgrep -f /data/server/login/p8_app_server"
      register: login_stat
      ignore_errors: yes
      tags:
        - login-start

    - name: login失败处理
      fail:
        msg: "login启动失败"
      when: login_stat.rc != 0
      tags:
        - login-start