- name: 复制文件
  shell: "command cp -rf /data/update/app/* /data/center/{{ zk_item }}/"
  tags:
    - alldo

- name: 过滤 zk 进程
  shell: pgrep -af '/data/center/{{ zk_item }}/p8_app_server'
  register: zk_stat
  ignore_errors: yes
  tags:
    - alldo

- name: Reload zk 进程（若存在）
  shell: "./server.sh reload && sleep 1 && ./server.sh reload"
  args:
    chdir: "/data/center/{{ zk_item }}"
  when: zk_stat.rc == 0
  tags:
    - alldo