- name: 复制文件
  copy:
    src: /data/update/app/
    dest: /data/server/{{ gate_item }}/
    remote_src: yes

- name: 过滤 gate 进程
  shell: pgrep -af '/data/server/{{ gate_item }}/p8_app_server'
  register: gate_stat
  ignore_errors: yes

- name: Reload gate 进程（若存在）
  shell: "./server.sh reload && sleep 1 && ./server.sh reload"
  args:
    chdir: "/data/server/{{ gate_item }}"
  when: gate_stat.rc == 0