- name: 1-0 如果不存在则创建 /data/update 目录
  file:
    path: /data/update
    state: directory
    mode: '0755'

- name: 1-1 分发文件
  copy:
    src: "{{ common_dir }}/common.zip"
    dest: /data/update/common.zip

- name: 1-2 创建解压目录
  file:
    path: /data/server/gate
    state: directory
    mode: '0755'

- name: 1-3 解压文件
  unarchive:
    src: /data/update/common.zip
    dest: /data/server/gate
    remote_src: yes

- name: 1-4 复制 etc 下server.log.ini和server.lua
  copy:
    src: "{{ item }}"
    dest: "/data/server/gate/etc/{{ item | basename }}"
  loop:
    - "{{ common_dir }}/etc/server.log.ini"
    - "{{ common_dir }}/etc/server.lua"

- name: 1-5 修改权限
  shell: |
    find /data/server -type f -exec chmod 644 {} \;
    find /data/server -type d -exec chmod 755 {} \;

- name: 1-6 复制 server.app.lua.j2
  template:
    src: server.app.lua.j2
    dest: "/data/server/gate/etc/server.app.lua"

- name: 1-7 增加执行权限
  file:
    path: "{{ item }}"
    mode: '0744'
  loop:
    - /data/server/gate/p8_app_server
    - /data/server/gate/server.sh

- name: 1-8 执行 /data/server/gate/server.sh start
  shell: "cd /data/server/gate/ && ./server.sh start && sleep 3"

- name: 1-9 检测进程状态
  shell: "pgrep -f /data/server/gate/p8_app_server"
  register: start_stat
  ignore_errors: yes

- name: 1-10 如果检测不到进程，退出剧本
  fail:
    msg: "服务启动失败，已尝试启动但无进程"
  when: start_stat.rc != 0
