- hosts: gm
  tasks:
    - name: 检查 gm 目录
      shell: "find /data/ -maxdepth 1 -type d -name 'gmserver[0-9]*' -printf '%f\n'"
      register: gm_list
      changed_when: false
      tags:
        - stop
        - start

    - name: 动态处理 gm 实例
      include_tasks: gm.yaml
      loop: "{{ gm_list.stdout_lines }}"
      loop_control:
        loop_var: gm_item
      tags:
        - stop
        - start