- name: 过滤 gm 进程
  shell: pgrep -af '/data/{{ gm_item }}/p8_app_server'
  register: gm_stat
  ignore_errors: yes
  tags:
    - stop

- name: stop gm 进程（若存在）
  shell: "./server.sh flush && sleep 10 && ./server.sh stop"
  args:
    chdir: "/data/{{ gm_item }}/"
  when: gm_stat.rc == 0
  tags:
    - stop

- name: start gm 进程
  shell: "./server.sh start"
  args:
    chdir: "/data/{{ gm_item }}/"
  tags:
    - start
