- name: 复制文件
  copy:
    src: /data/update/app/
    dest: /data/server/{{ login_item }}/
    remote_src: yes

- name: 过滤 login 进程
  shell: pgrep -af '/data/server/{{ login_item }}/p8_app_server'
  register: login_stat
  ignore_errors: yes

- name: Reload login 进程（若存在）
  shell: "./server.sh reload && sleep 1 && ./server.sh reload"
  args:
    chdir: "/data/server/{{ login_item }}"
  when: login_stat.rc == 0