- hosts: login
  tasks:
    - name: 检查 login 目录
      shell: "find /data/server -maxdepth 1 -type d -name 'login*' -printf '%f\n'"
      register: login_list
      changed_when: false

    - name: 分发更新压缩包
      copy:
        src: "{{ playbook_dir }}/../../file/all.tar.gz"
        dest: /data/update/all.tar.gz

    - name: 删除原本的 app 目录
      file:
        path: /data/update/app
        state: absent

    - name: 执行解压
      unarchive:
        src: /data/update/all.tar.gz
        dest: /data/update/
        remote_src: yes

    - name: 动态处理 login 实例
      include_tasks: login.yaml
      loop: "{{ login_list.stdout_lines }}"
      loop_control:
        loop_var: login_item