- name: 1-1 如果不存在则创建 /data/update 目录
  file:
    path: /data/update
    state: directory
    mode: '0755'
  tags:
    - base
    - start

- name: 1-2 分发文件
  copy:
<<<<<<< HEAD
    src: install.zip
    dest: /data/update/install.zip
=======
    src: install.tar.gz
    dest: /data/update/install.tar.gz
>>>>>>> dev
  tags:
    - base
    - start

- name: 1-3 创建解压目录
  file:
<<<<<<< HEAD
    path: "/data/server{{ area_id }}/game/"
=======
    path: "/data/tmp_create_game{{ area_id }}/"
>>>>>>> dev
    state: directory
    mode: '0755'
  tags:
    - base
    - start

- name: 1-4 解压文件
  unarchive:
<<<<<<< HEAD
    src: /data/update/install.zip
    dest: "/data/server{{ area_id }}/game/"
=======
    src: /data/update/install.tar.gz
    dest: "/data/tmp_create_game{{ area_id }}/"
>>>>>>> dev
    remote_src: yes
  tags:
    - base
    - start

<<<<<<< HEAD
- name: 1-5 修改权限
  shell: |
    find /data/server{{ area_id }} -type f -exec chmod 644 {} \;
    find /data/server{{ area_id }} -type d -exec chmod 755 {} \;
=======
- name: 1-5 删除旧的 last_time.db last_time.db.gc last_time.db.map open_time.lua
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "/data/tmp_create_game{{ area_id }}/lua/config/open_time.lua"
    - "/data/tmp_create_game{{ area_id }}/lua/config/last_time.db"
    - "/data/tmp_create_game{{ area_id }}/lua/config/last_time.db.gc"
    - "/data/tmp_create_game{{ area_id }}/lua/config/last_time.db.map"
  tags:
    - base
    - start
        
- name: 1-6 修改权限
  shell: |
    find /data/tmp_create_game{{ area_id }} -type f -exec chmod 644 {} \;
    find /data/tmp_create_game{{ area_id }} -type d -exec chmod 755 {} \;
>>>>>>> dev
  tags:
    - base
    - start

<<<<<<< HEAD
- name: 1-6 复制 server.app.lua.j2 和 zones.lua.j2
  template:
    src: "{{ item }}.j2"
    dest: "/data/server{{ area_id }}/game/etc/{{ item }}"
=======
- name: 1-7 复制 server.app.lua.j2 和 zones.lua.j2
  template:
    src: "{{ item }}.j2"
    dest: "/data/tmp_create_game{{ area_id }}/etc/{{ item }}"
>>>>>>> dev
  loop:
    - server.app.lua
    - zones.lua
  tags:
    - base
    - start

<<<<<<< HEAD
- name: 1-7 复制 open_time.lua.j2
  template:
    src: open_time.lua.j2
    dest: "/data/server{{ area_id }}/game/lua/config/open_time.lua"
=======
- name: 1-8 复制 open_time.lua.j2
  template:
    src: open_time.lua.j2
    dest: "/data/tmp_create_game{{ area_id }}/lua/config/open_time.lua"
>>>>>>> dev
  tags:
    - base
    - start

<<<<<<< HEAD
- name: 1-8 增加执行权限
=======
- name: 1-9 增加执行权限
>>>>>>> dev
  file:
    path: "{{ item }}"
    mode: '0755'
  loop:
<<<<<<< HEAD
    - "/data/server{{ area_id }}/game/p8_app_server"
    - "/data/server{{ area_id }}/game/server.sh"
=======
    - "/data/tmp_create_game{{ area_id }}/p8_app_server"
    - "/data/tmp_create_game{{ area_id }}/server.sh"
>>>>>>> dev
  tags:
    - base
    - start

<<<<<<< HEAD
- name: 1-9 执行 /data/server{{ area_id }}/game/server.sh start
=======
- name: 1-10 创建解压目录
  file:
    path: "/data/server{{ area_id }}/game/"
    state: directory
    mode: '0755'
  tags:
    - base
    - start

- name: 1-11 移动目录
  shell: |
      mv /data/tmp_create_game{{ area_id }}/* /data/server{{ area_id }}/game
      rm -rf /data/tmp_create_game{{ area_id }}/
  tags:
    - base
    - start

- name: 1-12 执行 /data/server{{ area_id }}/game/server.sh start
>>>>>>> dev
  shell: "./server.sh start"
  args:
    chdir: "/data/server{{ area_id }}/game/"
  tags:
    - start

- name: 睡 3 秒
  pause:
    seconds: 3
  tags:
    - base
    - start

<<<<<<< HEAD
- name: 1-10 检测进程状态
=======
- name: 1-13 检测进程状态
>>>>>>> dev
  shell: "pgrep -f /data/server{{ area_id }}/game/p8_app_server"
  register: start_stat
  ignore_errors: yes
  tags:
    - start

<<<<<<< HEAD
- name: 1-11 如果检测不到进程，退出剧本
=======
- name: 1-14 如果检测不到进程，退出剧本
>>>>>>> dev
  fail:
    msg: "服务启动失败，已尝试启动但无进程"
  when: start_stat.rc != 0
  tags:
<<<<<<< HEAD
    - start
=======
    - start
>>>>>>> dev
