- name: 1-1 如果不存在则创建 /data/update 目录
  file:
    path: /data/update
    state: directory
    mode: '0755'

- name: 1-2 分发文件
  copy:
    src: "{{ common_dir }}/common.zip"
    dest: /data/update/common.zip

- name: 1-3 创建解压目录
  file:
    path: /data/server{{ area_id }}/game
    state: directory
    mode: '0755'

- name: 1-4 解压文件
  unarchive:
    src: /data/update/common.zip
    dest: /data/server{{ area_id }}/game
    remote_src: yes

- name: 1-5 复制server.log.ini、server.lua、services.lua文件
  copy:
    src: "{{ item }}"
    dest: "/data/server{{ area_id }}/game/etc/{{ item | basename }}" 
  loop:
    - "{{ common_dir }}/etc/server.log.ini"
    - "{{ common_dir }}/etc/server.lua"
    - "{{ common_dir }}/etc/services.lua"

- name: 1-6 修改权限
  shell: |
    find /data/server{{ area_id }} -type f -exec chmod 644 {} \;
    find /data/server{{ area_id }} -type d -exec chmod 755 {} \;

- name: 1-7 复制 server.app.lua.j2 和 zones.lua.j2
  template:
    src: "{{ item }}.j2"
    dest: "/data/server{{ area_id }}/game/etc/{{ item }}"
  loop:
    - server.app.lua
    - zones.lua

- name: 1-8 增加执行权限
  file:
    path: "{{ item }}"
    mode: '0744'
  loop:
    - /data/server{{ area_id }}/game/p8_app_server
    - /data/server{{ area_id }}/game/server.sh

- name: 1-9 执行 /data/server{{ area_id }}/game/server.sh start
  shell: "./server.sh start && sleep 3"
  args:
    chdir: /data/server{{ area_id }}/game/

- name: 1-10 检测进程状态
  shell: "pgrep -f /data/server{{ area_id }}/game/p8_app_server"
  register: start_stat
  ignore_errors: yes

- name: 1-11 如果检测不到进程，退出剧本
  fail:
    msg: "服务启动失败，已尝试启动但无进程"
  when: start_stat.rc != 0
