- name: 1-1 如果不存在则创建 /data/update 目录
  file:
    path: /data/update
    state: directory
    mode: '0755'

- name: 1-2 分发文件
  copy:
    src: "{{ install_dir }}/install.zip"
    dest: /data/update/install.zip