- hosts: global
  tasks:
    - name: 检查 global 目录
      shell: "find /data/center/ -maxdepth 1 -type d -name 'global[0-9]*' -printf '%f\n'"
      register: global_list
      changed_when: false
      tags:
        - stop
        - start

    - name: 动态处理 global 实例
      include_tasks: global.yaml
      loop: "{{ global_list.stdout_lines }}"
      loop_control:
        loop_var: global_item
      tags:
        - stop
        - start