- name: 过滤 global 进程
  shell: pgrep -af '/data/center/{{ global_item }}/p8_app_server'
  register: global_stat
  ignore_errors: yes
  tags:
    - stop

- name: stop global 进程（若存在）  
  shell: "./server.sh flush && sleep 10 && ./server.sh stop"
  args:
    chdir: "/data/center/{{ global_item }}/"
  when: global_stat.rc == 0
  tags:
    - stop

- name: start global 进程
  shell: "./server.sh start"
  args:
    chdir: "/data/center/{{ global_item }}/"
  tags:
    - start
