- hosts: "{{ host_name }}"
  tasks:
    # ========== 基础准备任务 ==========
    - name: 1.检查更新目录是否存在
      file:
        path: /data/update
        state: directory
        mode: '0755'

    - name: 2.删除旧full目录
      file:
        path: /data/update/full
        state: absent

    - name: 3.分发全量包
      copy:
        src: "{{ playbook_dir }}/file/full.zip"
        dest: /data/update/full.zip

    - name: 4.解压更新包
      unarchive:
        src: /data/update/full.zip
        dest: /data/update/
        remote_src: yes

    # ========== 停止gate/login ==========
    - name: 5-1.停止gate服务
      block:
        - name: 检测gate进程
          shell: "pgrep -f /data/server/gate/p8_app_server"
          register: gate_stat
          ignore_errors: yes

        - name: 执行停止gate
          shell: "./server.sh stop && sleep 3"
          args:
            chdir: /data/server/gate/
          when: gate_stat.rc == 0

    - name: 5-2.停止login服务
      block:
        - name: 检测login进程
          shell: "pgrep -f /data/server/login/p8_app_server"
          register: login_stat
          ignore_errors: yes

        - name: 执行停止login
          shell: "./server.sh stop && sleep 3"
          args:
            chdir: /data/server/login/
          when: login_stat.rc == 0

    - name: 6.login和gate复制更新包
      copy:
        src: /data/update/full/
        dest: "/data/server/{{ item }}/"
        remote_src: yes
      loop:
        - login
        - gate

    # ========== 处理每个game实例 ==========
    - name: 7.处理动态game实例
      include_tasks: sub_tasks.yml
      loop: "{{ game_servers | default([]) }}"
      loop_control:
        loop_var: server_id

    # ========== 启动gate/login ==========
    - name: 8.启动gate服务
      block:
        - name: 8-1.清理gate下nohup.txt
          file:
            path: /data/server/gate/nohup.txt
            state: absent

        - name: 8-2.启动gate
          shell: "./server.sh start && sleep 3"
          args:
            chdir: /data/server/gate/

        - name: 8-2.验证gate状态
          shell: "pgrep -f /data/server/gate/p8_app_server"
          register: gate_stat
          ignore_errors: yes

        - name: 8-2.gate失败时处理
          fail:
            msg: "gate启动失败"
          when: gate_stat.rc != 0

    - name: 9.启动login服务
      block:
        - name: 9-1.清理login下nohup.txt
          file:
            path: /data/server/login/nohup.txt
            state: absent

        - name: 9-1.启动login
          shell: "./server.sh start && sleep 3"
          args:
            chdir: /data/server/login/

        - name: 9-1.验证login状态
          shell: "pgrep -f /data/server/login/p8_app_server"
          register: login_stat
          ignore_errors: yes

        - name: 9-1.login失败处理
          fail:
            msg: "login启动失败"
          when: login_stat.rc != 0