name: 'github actions  mirror'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mirror_to_gitlab:
    name: 'mirror to gitlab'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: 'mirror to gitlab'
        uses: yesolutions/mirror-action@v0.7.0
        with:
          # REMOTE: git@gitlab.com:${{ github.repository }}.git
          REMOTE: git@gitlab.com/z177859110333/finger.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CLAW_SYNC_PRIMARY_KEY }}
          PUSH_ALL_REFS: false
          GIT_SSH_NO_VERIFY_HOST: true
