name: 'github actions mirror'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  mirror_to_gitlab:
    name: 'mirror to gitlab'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: 'mirror to gitlab'
        uses: fscarmen/repository-mirroring-action@v1.0.0
        with:
          target_repo_url:
            # git@gitlab.com:${{ github.repository }}.git
            git@gitlab.com:z177859110333/finger.git
          ssh_private_key:
            ${{ secrets.CLAW_SYNC_PRIMARY_KEY }}
